---
- name:  Install NTP package
  yum:
    - name: "" {{service_name}} ""
      state: present
- name: configure ntp
  lineinfile:
    path: /etc/ntp.conf
    regexp: '^server'
    line: 'server 0.africa.pool.ntp.org'
  notify: restart ntpd
- name: start ntp service
  service:
    name: "" {{service_name}} ""
    state: started
    enabled: yes
- name: set timezone
  timezone:
    name: Africa/Cairo
    state: present 
